from tkinter import *
root=Tk()
def exit():
    root.destroy()
a=Label(root,text="AGE CALCULATOR",font=("Arial",20), fg="red").place(x=150,y=10)
a1=Label(root,text="NAME:",font=('Arial',10,"bold"),fg="red",bg="skyblue").place(x=150,y=78)
a3=Label(root,text="DATE:",font=('Arial',10,"bold"),fg="red",bg="skyblue").place(x=150,y=120)
a4=Label(root,text="MONTH:",font=('Arial',10,"bold"),fg="red",bg="skyblue").place(x=150,y=160)
a5=Label(root,text="YEAR:",font=('Arial',10,"bold"),fg="red",bg="skyblue").place(x=150,y=200)
a6=Label(root,text="MOBILE:",font=('Arial',10,"bold"),fg="red",bg="skyblue").place(x=150,y=240)
w=Entry(root, width=15).place(x=225,y=78)
w2=Entry(root, width=15).place(x=225,y=120)
w3=Entry(root, width=15).place(x=225,y=160)
w4=Entry(root, width=15).place(x=225,y=200)
w5=Entry(root, width=15).place(x=225,y=240)
mybut=Button(root,text="submit",font=("Arial",13,"bold"),fg="black",bg="yellow").place(x=200,y=300)
mybut2=Button(root,text="Exit",command=exit,font=("Arial",13,"bold"),fg="black",bg="yellow").place(x=280,y=300)
root.title("Age Calculator")
root.geometry("600x600+40+40")
root.config(bg="skyblue")
root.resizable(width=False,height=False)
root.mainloop()